# Generated by Django 3.0.3 on 2020-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], default='access', max_length=25),
        ),
    ]
