# Generated by Django 3.0.3 on 2020-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rawnewreleases_sanitizednewrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizednewrelease',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
